/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//enable clock
typedef volatile unsigned int vuint32_t;
#include<stdint.h>
#include<stdlib.h>
#include<stdio.h>
// register address
//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA13 (1UL<<13)
// Rcc
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR *(volatile uint32_t *)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_BASE + 0x08)
//NVIC
#define NVIC_BASE 0xE000E100
#define NVIC_EXTIE0 *(volatile uint32_t *)(NVIC_BASE + 0x00)
void clock_init()
{
	//enable GPIOA
	RCC_APB2ENR |= 1<<2;
	//ENABLE AFIO0
	RCC_APB2ENR |= 1<<0;
}
void GPIOA_init()
{
	//bit 13 output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//pinA 0 input floating
	GPIOA_CRL |=(1<<2);
}
void EXTI_init()
{
	// enable EXTI0 to gpioA
	EXTI_IMR |= (1<<0);
	// enable rising trigger
	EXTI_RTSR |= (1<<0);

}
void AFIO_init()
{
	//EXTI) configration to portA0
	AFIO_EXTICR1 =0;
}
void NVIC_init()
{
	//enable NVIC IRQ6 <<>>EXTI0
	NVIC_EXTIE0 |= (1<<6);
}


int main(void)
{
	clock_init();
	GPIOA_init();
	EXTI_init();
	AFIO_init();
	NVIC_init();
	while(1);



}
void EXTI0_IRQHandler(void){
	//IRQ is happened EXTI0 >>> portA pin 0 _|- rising edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13);
	//clear interrupt
	EXTI_PR |= (1<<0);
}
