/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE+0x18))
//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *((volatile uint32_t*)(GPIOA_BASE+0x00))
#define GPIOA_CRH *((volatile uint32_t*)(GPIOA_BASE+0x04))
#define GPIOA_IDR *((volatile uint32_t*)(GPIOA_BASE+0x08))
#define GPIOA_ODR *((volatile uint32_t*)(GPIOA_BASE+0x0c))
//GPIOB
#define GPIOB_BASE 0x40010c00
#define GPIOB_CRL *((volatile uint32_t*)(GPIOB_BASE+0x00))
#define GPIOB_CRH *((volatile uint32_t*)(GPIOB_BASE+0x04))
#define GPIOB_IDR *((volatile uint32_t*)(GPIOB_BASE+0x08))
#define GPIOB_ODR *((volatile uint32_t*)(GPIOB_BASE+0x0c))

void RCC_init()
{
	//enable rcc pa
	RCC_APB2ENR |= 1<<2;
	//enable rcc pb
	RCC_APB2ENR |= 1<<3;
}
void GPIO_init()
{
	//pA1 input rest state
	GPIOA_CRL =0x0;
	GPIOA_CRL |= 1<<6;



	//pB1 (output push pull mode)
	GPIOB_CRL =0x0;
	GPIOB_CRL |= 1<<4;

	//pA 13 input reset state
	GPIOA_CRH =0x0;
	GPIOA_CRH |= 1<<22;


	//pB13 output open drain mode
	GPIOB_CRH=0x0;
	GPIOB_CRH |= 1<<22;
	GPIOB_CRH |= 1<<20;

}
void wait_ms(int x){
	int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}
int main(void)
{
	RCC_init();
	GPIO_init();

    while(1){
    	if(((GPIOA_IDR & (1<<1))>>1)==0) //single press
    	{
    		GPIOB_ODR ^= 1<<1;
    		while(((GPIOA_IDR & (1<<1))>>1)==0);
    	}
    	if(((GPIOA_IDR & (1<<13))>>13)==1) //multi press
    	    	{
    	    		GPIOB_ODR ^= 1<<13;

    	    	}
    	wait_ms(1);


    }
}
