/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "stm32f103c6.h"
#include "stm32f103c6_gpio_driver.h"
#include "lcd.h"
#include "keypad.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void clock_init() {
	//Enable clock GPIOA
	GPIOA_EN_CLK();
	//Enable clock GPIOB Bit 3 IOPBEN: IO port B clock enable
	GPIOB_EN_CLK();
}
void GPIO_init() {

	GPIO_PIN_Config_t pincfg;

	//PA1 input HighZ Floating input (reset state)
//	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
//	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
//	MCAL_GPIO_Init(GPIOA, &PinCfg);

//PB1 (output PUSH pull Mode)
//01: Output mode, max speed 10 MHz.
//CNF 00: General purpose output push-pull
	pincfg.GPIO_pin_number = GPIO_PIN_9;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
	pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	pincfg.GPIO_pin_number = GPIO_PIN_10;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	pincfg.GPIO_pin_number = GPIO_PIN_11;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	pincfg.GPIO_pin_number = GPIO_PIN_12;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	pincfg.GPIO_pin_number = GPIO_PIN_13;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	//============================

	//PA13 input HighZ Floating input (reset state)
	pincfg.GPIO_pin_number = GPIO_PIN_14;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

	//PB13 (output PUSH pull Mode)
	pincfg.GPIO_pin_number = GPIO_PIN_15;
	pincfg.GPIO_mode = GPIO_mode_OUTPUT_PP;
		pincfg.GPIO_speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);

}
extern void wait_ms();
int main(void) {

	clock_init();
	lcd_init();
	unsigned char key_pressed;
	lcd_send_string("HEY");
	wait_ms(30);
	lcd_clear_screen();
	GPIO_init();
	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	for (unsigned char i = 0; i < 11; i++) {
		lcd_send_char(LCD_DISPLAY[i]);
		MCAL_GPIO_WRITE_PORT(GPIOB, DISPLAY[i] << 9); /* write data on to the LED port */
		wait_ms(100);
		/* wait for 1 second */
	}
//	MCAL_GPIO_WritePort(GPIOB, 0xDE);
//	wait_ms(100);
	lcd_clear_screen();
	Keypad_init();
	lcd_send_string ("Keypad is ready");
	wait_ms(30);
	lcd_clear_screen();

	while (1) {

		key_pressed = Keypad_getkey();
		switch (key_pressed) {
		case 'A':
			break;
		case '?':
			lcd_clear_screen();
			break;
		default:
			lcd_send_char(key_pressed);
			break;
		}
//		//PA1 >>>Connected external PUR
//
//		if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // press
//		{
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
//			while  (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)  ; //Single Pressing
//		}
//		//PA13 >>>Connected external PDR
//		if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) //Multi Pressing
//		{
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
//		}
//		LCD_WRITE_STRING("HEY");
//		wait_ms(30);
//		LCD_clear_screen();
	}
}

